apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scalebiz.fullname" . }}-env
  labels:
    {{- include "scalebiz.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.global.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
