/**
 * Property-Based Test — Property 5: Auth Endpoint Canonical
 *
 * **Validates: Requirements 9.8, 9.9 (Property 5 — design.md "Correctness Properties")**
 *
 * Property 5 statement (design.md line 421):
 *   "Login/register hanya melalui `POST /auth/sign-in/email` dan
 *    `POST /auth/sign-up/email`; tidak ada panggilan ke `/api/auth/login`
 *    atau variannya."
 *
 * System under test:
 *   The frontend source tree at `apps/frontend/src/**\/*.{ts,tsx}`. The
 *   property is a STATIC source invariant: no source file may contain the
 *   literal substring `/api/auth/login` (or its variants `register`,
 *   `signin`, `signup`), and the canonical Better Auth call sites must
 *   use exactly `/sign-in/email` and `/sign-up/email`.
 *
 * Scope clarification (strict literal scan):
 *   `apps/frontend/src/lib/api.ts:316` exports an `auth.login()` helper
 *   that calls `apiRequest('/auth/login', ...)`. At runtime, `apiRequest`
 *   prepends `${API_BASE}` (which is `/api`), so the resolved URL becomes
 *   `POST /api/auth/login`. This concatenation happens at runtime — the
 *   literal substring `/api/auth/login` does NOT appear in any source
 *   file. Property 5 is a STATIC source-text property (per task 14.3
 *   "scan source frontend untuk pattern `/api/auth/login` atau varian"),
 *   so the parity-locked `auth.login()` helper is OUT OF SCOPE for this
 *   test. It is documented as a known finding in
 *   `notes/test-report.md` for transparency.
 *
 * Forbidden literal patterns (the `/api/auth/*` family, all "/api/" prefixed):
 *   /api/auth/login
 *   /api/auth/register
 *   /api/auth/signin
 *   /api/auth/signup
 *   /api/auth/sign-in        (non-canonical — canonical is `/auth/sign-in/email`)
 *   /api/auth/sign-up        (same — canonical is `/auth/sign-up/email`)
 *   /auth/sign-in/email-password   (legacy non-canonical variant flagged in design.md)
 *   /auth/sign-up/email-password   (same)
 *
 * Properties (formalised):
 *
 *   Let S = { source text of every `.ts`/`.tsx` file under
 *             `apps/frontend/src/`, excluding `routeTree.gen.ts` and
 *             `.ts.bak*` files }.
 *   Let F = the forbidden literal pattern set above.
 *   Let canonical_signin  = "/sign-in/email"
 *   Let canonical_signup  = "/sign-up/email"
 *
 *   P5a (∀-property over source × forbidden):
 *     ∀ file ∈ S, ∀ pat ∈ F   :   pat ∉ file
 *
 *   P5b (canonical positive presence):
 *     "login.tsx" CONTAINS the substring canonical_signin
 *     "register.tsx" CONTAINS the substring canonical_signup
 *     AND both files use a `fetch(...)` call (not `apiRequest`) for the
 *     auth call, per design.md section 5 "credentials: 'include'".
 *
 *   P5c (random sampling):
 *     Pick ≥120 (file, pattern) pairs at random from S × F. For each
 *     picked pair, assert pattern is absent from file. Random sampling
 *     gives reproducible counterexamples for a ∀-property; the
 *     deterministic batch in P5a remains the primary correctness check.
 *
 * Random generation uses a deterministic Mulberry32 PRNG seeded from the
 * env var `OPENCRM_PROP_SEED` (default `0xC0FFEE`) so failing runs are
 * reproducible. NO new npm dependency (parity rule). Same PRNG pattern
 * as `apps/backend/test/parity/workspace.test.ts` (Property 1) and
 * `apps/frontend/test/parity/navigation.test.ts` (Property 4).
 *
 * Test runner: `bun test` (matches monorepo convention).
 */

import { describe, expect, it } from 'bun:test'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'

// ---------- canonical sets (from design.md Property 5 + task 14.3) ----------

const FORBIDDEN_PATTERNS: readonly string[] = [
	'/api/auth/login',
	'/api/auth/register',
	'/api/auth/signin',
	'/api/auth/signup',
	'/api/auth/sign-in',
	'/api/auth/sign-up',
	'/auth/sign-in/email-password',
	'/auth/sign-up/email-password',
] as const

const CANONICAL_SIGNIN = '/sign-in/email'
const CANONICAL_SIGNUP = '/sign-up/email'

// ---------- source tree walker ----------

const FRONTEND_SRC = join(__dirname, '..', '..', 'src')

/**
 * Recursively walk the frontend src tree and return every `.ts`/`.tsx`
 * file path. We deliberately:
 *   - exclude `routeTree.gen.ts` (auto-generated by TanStack Router)
 *   - exclude `.bak` / `.bak2` / `.bak3` files (these are *.ts.bak, not
 *     *.ts, but we double-check by extension match)
 *   - exclude any `node_modules` if encountered (defensive)
 *
 * Returns absolute paths, sorted for stable iteration.
 */
function listSourceFiles(root: string): string[] {
	const out: string[] = []
	const stack: string[] = [root]
	while (stack.length > 0) {
		const dir = stack.pop()!
		const entries = readdirSync(dir, { withFileTypes: true })
		for (const ent of entries) {
			const full = join(dir, ent.name)
			if (ent.isDirectory()) {
				if (ent.name === 'node_modules') continue
				stack.push(full)
				continue
			}
			if (!ent.isFile()) continue
			// strict extension match — `.ts` or `.tsx`. This excludes
			// `api.ts.bak`, `api.ts.bak2`, `api.ts.bak3` because their
			// extension is `.bak`/`.bak2`/`.bak3`, not `.ts`.
			if (!(ent.name.endsWith('.ts') || ent.name.endsWith('.tsx'))) continue
			if (ent.name === 'routeTree.gen.ts') continue
			out.push(full)
		}
	}
	return out.sort()
}

/**
 * Read a file's text content (utf-8). Cached at module scope so each
 * test reads each file at most once.
 */
const fileCache = new Map<string, string>()
function readSrc(path: string): string {
	let text = fileCache.get(path)
	if (text === undefined) {
		text = readFileSync(path, 'utf-8')
		fileCache.set(path, text)
	}
	return text
}

/**
 * For a counterexample, find the line number of the FIRST occurrence of
 * `needle` in `text`. Returns `{ line, content }` or null.
 */
function findFirstHit(
	text: string,
	needle: string,
): { line: number; content: string } | null {
	const lines = text.split('\n')
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i] as string
		if (line.includes(needle)) {
			return { line: i + 1, content: line.trim() }
		}
	}
	return null
}

// ---------- deterministic PRNG (Mulberry32) ----------

function makeRng(seed: number) {
	let state = seed >>> 0
	return () => {
		state = (state + 0x6d2b79f5) >>> 0
		let t = state
		t = Math.imul(t ^ (t >>> 15), t | 1)
		t ^= t + Math.imul(t ^ (t >>> 7), t | 61)
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296
	}
}

const SEED = Number(process.env.OPENCRM_PROP_SEED ?? 0xc0ffee)
const rng = makeRng(SEED)

function pick<T>(arr: readonly T[]): T {
	return arr[Math.floor(rng() * arr.length)] as T
}

// ---------- the property test ----------

const N_PROPERTIES = Number(process.env.OPENCRM_PROP_COUNT ?? 120)

describe('Property 5 — Auth Endpoint Canonical (frontend source scan)', () => {
	const sourceFiles = listSourceFiles(FRONTEND_SRC)

	it('frontend src tree is non-empty and reachable', () => {
		// Sanity: the walker must have found something. If `apps/frontend/src`
		// disappears or moves, this test must not silently pass.
		expect(statSync(FRONTEND_SRC).isDirectory()).toBe(true)
		expect(sourceFiles.length).toBeGreaterThan(20)
	})

	it('P5a — no source file contains any forbidden /api/auth/* literal pattern', () => {
		const counterexamples: Array<{
			file: string
			pattern: string
			line: number
			content: string
		}> = []

		for (const file of sourceFiles) {
			const text = readSrc(file)
			for (const pat of FORBIDDEN_PATTERNS) {
				if (text.includes(pat)) {
					const hit = findFirstHit(text, pat)
					counterexamples.push({
						file: relative(FRONTEND_SRC, file),
						pattern: pat,
						line: hit?.line ?? -1,
						content: hit?.content ?? '<unknown>',
					})
				}
			}
		}

		if (counterexamples.length > 0) {
			// eslint-disable-next-line no-console
			console.error(
				`\n[Property 5a] ${counterexamples.length} counterexample(s):\n` +
					counterexamples
						.map(
							(c, idx) =>
								`  #${idx + 1} file=${c.file}:${c.line}\n` +
								`     pattern="${c.pattern}"\n` +
								`     content=${c.content}`,
						)
						.join('\n'),
			)
		}

		expect(counterexamples).toEqual([])
	})

	it('P5b — login.tsx uses canonical `${AUTH_BASE}/sign-in/email` via fetch()', () => {
		const loginPath = join(FRONTEND_SRC, 'routes', 'login.tsx')
		const text = readSrc(loginPath)

		// Must contain the canonical signin path
		expect(text.includes(CANONICAL_SIGNIN)).toBe(true)
		// Must use `fetch(` (not apiRequest) — auth root endpoints don't go
		// through `/api` per design.md section 9.8.
		expect(text.includes('fetch(')).toBe(true)
		// AUTH_BASE constant scoped to root Better Auth (`${VITE_API_URL}/auth`)
		expect(text.includes('AUTH_BASE')).toBe(true)
		expect(text.includes('/auth')).toBe(true)
		// credentials: 'include' is required (Better Auth root endpoints set
		// session cookie). This is also asserted by Property 5 callsites.
		expect(text.includes("credentials: 'include'")).toBe(true)

		// Negative: login.tsx itself must not contain any forbidden literal
		for (const pat of FORBIDDEN_PATTERNS) {
			expect({ pat, hit: text.includes(pat) }).toEqual({ pat, hit: false })
		}
	})

	it('P5b — register.tsx uses canonical `${AUTH_BASE}/sign-up/email` via fetch()', () => {
		const registerPath = join(FRONTEND_SRC, 'routes', 'register.tsx')
		const text = readSrc(registerPath)

		expect(text.includes(CANONICAL_SIGNUP)).toBe(true)
		expect(text.includes('fetch(')).toBe(true)
		expect(text.includes('AUTH_BASE')).toBe(true)
		expect(text.includes('/auth')).toBe(true)
		expect(text.includes("credentials: 'include'")).toBe(true)

		for (const pat of FORBIDDEN_PATTERNS) {
			expect({ pat, hit: text.includes(pat) }).toEqual({ pat, hit: false })
		}
	})

	it(`P5c — ${N_PROPERTIES} random (file, pattern) pairs are absent`, () => {
		const counterexamples: Array<{
			iter: number
			file: string
			pattern: string
			line: number
			content: string
		}> = []

		const fileHits: Record<string, number> = {}
		const patHits: Record<string, number> = {}

		for (let i = 0; i < N_PROPERTIES; i++) {
			const file = pick(sourceFiles)
			const pat = pick(FORBIDDEN_PATTERNS)
			const rel = relative(FRONTEND_SRC, file)
			fileHits[rel] = (fileHits[rel] ?? 0) + 1
			patHits[pat] = (patHits[pat] ?? 0) + 1

			const text = readSrc(file)
			if (text.includes(pat)) {
				const hit = findFirstHit(text, pat)
				counterexamples.push({
					iter: i,
					file: rel,
					pattern: pat,
					line: hit?.line ?? -1,
					content: hit?.content ?? '<unknown>',
				})
			}
		}

		if (counterexamples.length > 0) {
			// eslint-disable-next-line no-console
			console.error(
				`\n[Property 5c] ${counterexamples.length} counterexample(s) of ${N_PROPERTIES} iterations:\n` +
					counterexamples
						.slice(0, 5)
						.map(
							(c, idx) =>
								`  #${idx + 1} iter=${c.iter} file=${c.file}:${c.line}\n` +
								`     pattern="${c.pattern}"\n` +
								`     content=${c.content}`,
						)
						.join('\n'),
			)
		}

		// Sanity: random batch covered all 8 forbidden patterns. With 120
		// iters across 8 patterns, probability of missing any one is
		// (7/8)^120 ≈ 1.4e-7, so this assertion is safe.
		const patternsCovered = Object.keys(patHits).length
		expect(patternsCovered).toBe(FORBIDDEN_PATTERNS.length)

		expect(counterexamples).toEqual([])
	})

	it('boundary spot-checks: every (login.tsx|register.tsx) × forbidden pattern pair is independently absent', () => {
		// Belt-and-suspenders deterministic check on the two canonical auth
		// callsites. If any of these ever leaks a forbidden pattern, this
		// test surfaces the offender by name without needing a specific seed.
		const loginText = readSrc(join(FRONTEND_SRC, 'routes', 'login.tsx'))
		const registerText = readSrc(join(FRONTEND_SRC, 'routes', 'register.tsx'))

		for (const pat of FORBIDDEN_PATTERNS) {
			const hitLogin = findFirstHit(loginText, pat)
			expect({ file: 'routes/login.tsx', pat, hit: hitLogin }).toEqual({
				file: 'routes/login.tsx',
				pat,
				hit: null,
			})
			const hitReg = findFirstHit(registerText, pat)
			expect({ file: 'routes/register.tsx', pat, hit: hitReg }).toEqual({
				file: 'routes/register.tsx',
				pat,
				hit: null,
			})
		}
	})

	it('coverage report — number of source files scanned ≥ 20', () => {
		// Surface coverage for the test report. This is a soft gate — the
		// real assertion is in P5a/P5c, but emitting a number to stderr
		// makes the test-report.md richer.
		// eslint-disable-next-line no-console
		console.error(
			`[Property 5] Scanned ${sourceFiles.length} .ts/.tsx files under apps/frontend/src/ (excluded routeTree.gen.ts and *.ts.bak*).`,
		)
		expect(sourceFiles.length).toBeGreaterThanOrEqual(20)
	})
})
